### ISSUE TITLE
Microservices in a Post-Kubernetes Era

### ISSUE THREAD

**Issue by rootsongjc** [servicemesher/trans#100]
## 基本信息

原文链接：https://www.infoq.com/articles/microservices-post-kubernetes

发布时间：2018年9月1日

译文链接：

作者：Bilgin Ibryam 

译者：

类型：博客

**Comment by loverto** [comment]
认领

**Comment by rootsongjc** [comment]
认领这篇文章要小心，因为极有可能会被InfoQ的人提前翻译了。前车之鉴，见https://github.com/servicemesher/trans/issues/96

**Comment by loverto** [comment]
好有压力
