### ISSUE TITLE
envoy stats

### ISSUE THREAD

**Issue by moeyui1** [servicemesher/trans#110]
## 基本信息

原文链接：https://blog.envoyproxy.io/envoy-stats-b65c7f363342

发布时间：2017年8月20日

译文链接：

作者：Matt Klein

译者：王帅俭

类型：博客

**Comment by gzzengwei** [comment]
I will take this one.

**Comment by moeyui1** [comment]
thx

**Comment by rootsongjc** [comment]
@gzzengwei 这篇文章认领已经有快一个月，还没有PR，原则上每篇文章认领后要在5天内提交。如果今晚还没有提交的话明天就重新分配。

**Comment by jianzi123** [comment]
这个有人在弄吗

**Comment by rootsongjc** [comment]
@moeyui1 一直没有提交，重新分配吧。

**Comment by rootsongjc** [comment]
@jianzi123 已经过去23天了，是否翻译完成？如果完成了请尽快提交。

**Comment by jianzi123** [comment]
ok

**Comment by jianzi123** [comment]
@rootsongjc 宋总最近有点忙，周末差不多提交。

**Comment by rootsongjc** [comment]
@jianzi123 已经过去1个多月，还不提交吗？

**Comment by jianzi123** [comment]
ok
