### ISSUE TITLE
nginx-ingress vs kong vs traefik vs haproxy vs voyager vs contour vs ambassador vs istio ingress

### ISSUE THREAD

**Issue by rootsongjc** [servicemesher/trans#113]
## 基本信息

原文链接：https://kubedex.com/nginx-ingress-vs-kong-vs-traefik-vs-haproxy-vs-voyager-vs-contour-vs-ambassador/

发布时间：2018年9月11日

译文链接：

作者：Steven Acreman

译者：甄中元

类型：博客

**Comment by meua** [comment]
认领
