### ISSUE TITLE
Serverless Jenkins with Jenkins X

### ISSUE THREAD

**Issue by rootsongjc** [servicemesher/trans#133]
## 基本信息

原文链接：https://medium.com/@jdrawlings/serverless-jenkins-with-jenkins-x-9134cbfe6870

发布时间：2018年10月19日

译文链接：https://my.oschina.net/u/1262062/blog/2251122

作者：James Rowlings

译者：王凯

类型：博客

**Comment by yiduwangkai** [comment]
怎么给malphi了？

**Comment by rootsongjc** [comment]
@yiduwangkai 不好意思，看花眼了。另外你还没加入到ServiceMesher GitHub组织里，是无法领取任务的。请先入GitHub社区，我邀请你加入GitHub组织里。

**Comment by yiduwangkai** [comment]
已经加入了

**Comment by malphi** [comment]
> 怎么给malphi了？

哈哈，他手滑了

**Comment by yiduwangkai** [comment]
已经在翻译中，进度有点慢见谅
https://my.oschina.net/u/1262062/blog/2251122

**Comment by rootsongjc** [comment]
@yiduwangkai 又过去一个月了，什么时候提交呢？
