### ISSUE TITLE
Istio + envoy + grpc + metrics winning with service mesh in practice!

### ISSUE THREAD

**Issue by yangchuansheng** [servicemesher/trans#147]
## 基本信息

原文链接：[https://medium.com/pismolabs/istio-envoy-grpc-metrics-winning-with-service-mesh-in-practice-d67a08acd8f7](https://medium.com/pismolabs/istio-envoy-grpc-metrics-winning-with-service-mesh-in-practice-d67a08acd8f7)

发布时间：2018年8月28日

译文链接：

作者：Renato Stoco

译者：陈冬

类型：博客

**Comment by rootsongjc** [comment]
@yangchuansheng 这个是你要认领吗？

**Comment by yangchuansheng** [comment]
@rootsongjc 这个我就不认领了，留给别人吧
