### ISSUE TITLE
Why is Service Mesh ?

### ISSUE THREAD

**Issue by yangchuansheng** [servicemesher/trans#157]
## 基本信息

原文链接：https://medium.com/@tak2siva/why-is-service-mesh-8ebcd6ed9eb5

发布时间：2018年11月6日

译文链接：

作者：shiva

译者：

类型：博客

**Comment by rootsongjc** [comment]
@yiduwangkai 已经 review 并合并了该 issue 的 PR，请 @yiduwangkai 同时上传到 website 中，注意 webiste 中文档的格式，参考之前提交的文档中的 front matter，有问题可以问我和 @yangchuansheng
