### ISSUE TITLE
Istio 1.0.2 (Envoy) + Cert-Manager + Let’s Encrypt for TLS + Certificate Merge

### ISSUE THREAD

**Issue by yangchuansheng** [servicemesher/trans#160]
## 基本信息

原文链接：https://medium.com/@prune998/istio-1-0-2-envoy-cert-manager-lets-encrypt-for-tls-certificate-merge-7a774bff66c2

发布时间：2018年11月8日

译文链接：

作者：Prune

译者：

类型：博客

**Comment by featen** [comment]
I can take this one.

**Comment by featen** [comment]
不好意思，最近实在腾不出手来翻译这个，而有点长，请另外assign一下，谢谢。

**Comment by rootsongjc** [comment]
取消指派，重新认领。

**Comment by haiker2011** [comment]
https://blog.csdn.net/yinlongfei_love/article/details/80745410 已经有相关文章翻译
