### ISSUE TITLE
Seamless Cloud-Native Apps with gRPC-Web and Istio

### ISSUE THREAD

**Issue by yangchuansheng** [servicemesher/trans#164]
## 基本信息

原文链接：https://venilnoronha.io/seamless-cloud-native-apps-with-grpc-web-and-istio

发布时间：2018年11月10日

译文链接：

作者：[Venil Noronha](https://venilnoronha.io/about/)

译者：王全根

类型：博客

**Comment by roganw** [comment]
领取

**Comment by rootsongjc** [comment]
@roganw 已经过了快一个月了，是否还在翻译，如果翻译完成请及时提交，如果没时间翻译可以让给其他人。
