### ISSUE TITLE
From Fragmented Microservices Ecosystem to Service Mesh

### ISSUE THREAD

**Issue by rootsongjc** [servicemesher/trans#176]
## 基本信息

原文链接：https://blog.avinetworks.com/from-fragmented-microservices-ecosystem-to-service-mesh

发布时间：2018年11月15日

译文链接：

作者：Manish Chugtu

译者：狄卫华

类型：博客、架构

**Comment by DavadDi** [comment]
认领

**Comment by rootsongjc** [comment]
@DavadDi 已经过了10多天了，是否还在翻译，如果翻译完成请及时提交，如果没时间翻译可以让给其他人。
