### ISSUE TITLE
Introducing AWS App Mesh – service mesh for microservices on AWS

### ISSUE THREAD

**Issue by rootsongjc** [servicemesher/trans#180]
## 基本信息

原文链接：https://aws.amazon.com/blogs/compute/introducing-aws-app-mesh-service-mesh-for-microservices-on-aws/

发布时间：2018年11月28日

译文链接：

作者：Nathan Taber

译者：

类型：博客

**Comment by haiker2011** [comment]
领取

**Comment by rootsongjc** [comment]
@haiker2011 这篇文章出来已经有好几个月了，翻译前请先确认下是否已经有比较完整的中文版，如果有的话就不用再翻译了，我们要尽量保证文章的时效性。

**Comment by haiker2011** [comment]
@rootsongjc 这篇文章确实有些旧了，而且官方有[https://aws.amazon.com/cn/app-mesh](https://aws.amazon.com/cn/app-mesh/)和[https://aws.amazon.com/cn/about-aws/whats-new/2018/11/introducing-aws-app-mesh---service-mesh-for-microservices-on-aws](https://aws.amazon.com/cn/about-aws/whats-new/2018/11/introducing-aws-app-mesh---service-mesh-for-microservices-on-aws/)两篇中文简介文章了，没有翻译的必要了。

**Comment by rootsongjc** [comment]
@haiker2011 这个 issue 可以关闭了，你可以认领其他文章或者提交原创文章到该 repo。
