### ISSUE TITLE
Envoy threading model

### ISSUE THREAD

**Issue by rootsongjc** [servicemesher/trans#186]
## 基本信息

原文链接：https://blog.envoyproxy.io/envoy-threading-model-a8d44b922310

发布时间：2017年7月30日

译文链接：

作者：Matt Klein

译者：

类型：博客

**Comment by yiduwangkai** [comment]
accept

**Comment by yiduwangkai** [comment]
@rootsongjc  i assigned by myself?

**Comment by rootsongjc** [comment]
@yiduwangkai 认领已经有一个多月了，是否可以提交？

**Comment by yiduwangkai** [comment]
过年期间我提交一下

**Comment by rootsongjc** [comment]
@yiduwangkai 现在进展怎么样了？

**Comment by yiduwangkai** [comment]
明天提交上去

**Comment by yiduwangkai** [comment]
周日已经翻译完，今天我提交一下
