### ISSUE TITLE
Microservices Circuit-Breaker Pattern Implementation: Istio vs Hystrix

### ISSUE THREAD

**Issue by yangchuansheng** [servicemesher/trans#190]
## 基本信息

原文链接：https://www.exoscale.com/syslog/istio-vs-hystrix-circuit-breaker/

发布时间：2018年12月13日

译文链接：

作者：[Nicolas Frankel](https://twitter.com/nicolas_frankel)

译者：

类型：博客

**Comment by GuangmingLuo** [comment]
领取
