### ISSUE TITLE
FaaS vs. Microservices

### ISSUE THREAD

**Issue by rootsongjc** [servicemesher/trans#193]
## 基本信息

原文链接：https://dzone.com/articles/faas-vs-microservices

发布时间：2018年12月17日

译文链接：

作者：Christian Posta

译者：

类型：博客

**Comment by saberuster** [comment]
认领

**Comment by rootsongjc** [comment]
@saberuster 你好，已经认领快一个月了，是否有进展？

**Comment by saberuster** [comment]
@rootsongjc 您好，翻译已接近尾声，最近一直在外地，所以耽搁了，计划明晚之前提交上来。
