### ISSUE TITLE
Kubernetes Operators — When, how and the gotchas to keep in mind

### ISSUE THREAD

**Issue by rootsongjc** [servicemesher/trans#195]
## 基本信息

原文链接：https://medium.com/@cloudark/kubernetes-operators-when-how-and-the-gotchas-to-keep-in-mind-b13be9830346

发布时间：2019年1月22日

译文链接：

作者：CloudArk

译者：

类型：博客

**Comment by jianzi123** [comment]
领取

**Comment by rootsongjc** [comment]
@jianzi123 已经认领有两个星期了，现在进展怎么样？

**Comment by jianzi123** [comment]
这几天赶紧弄一弄

**Comment by yiduwangkai** [comment]
operator使得kubernets和大数据的关系更紧密了

**Comment by GuangmingLuo** [comment]
@jianzi123 请问这篇文章最近还在翻译吗，进展怎么样了？

**Comment by haiker2011** [comment]
原始文章已经发布很久，没有时效性，建议关闭！
