### ISSUE TITLE
API Gateways Are Going Through an Identity Crisis

### ISSUE THREAD

**Issue by rootsongjc** [servicemesher/trans#197]
## 基本信息

原文链接：http://blog.christianposta.com/microservices/api-gateways-are-going-through-an-identity-crisis/

发布时间：2019年1月21日

译文链接：

作者：Christian Posta

译者：周雨青

类型：博客

**Comment by wikiios** [comment]
认领

**Comment by haiker2011** [comment]
@wikiios  已经认领有三个星期了，现在进展怎么样？

**Comment by wikiios** [comment]
sry, 已经翻译好了，这两天在出差，今晚提交文档

**Comment by haiker2011** [comment]
ok

**Comment by wikiios** [comment]
你好，为什么这文章发布了，译者不是我。。。

https://mp.weixin.qq.com/s/5W9BV3CVfvAmW_P6uXMzvg

**Comment by rootsongjc** [comment]
不好意思，译者搞错了，我去更正下。
