### ISSUE TITLE
Istio Service Mesh: The Step by Step Guide

### ISSUE THREAD

**Issue by rootsongjc** [servicemesher/trans#198]
## 基本信息

原文链接：https://itnext.io/istio-service-mesh-the-step-by-step-guide-adf6da18bb9a

发布时间：2019年1月18日

译文链接：

作者：Cuelogic Technologies

译者：

类型：教程

**Comment by yiduwangkai** [comment]
领取

**Comment by haiker2011** [comment]
@yiduwangkai  已经认领很长时间了，现在进展怎么样？

**Comment by haiker2011** [comment]
原始文章已经发布很久，没有时效性，建议关闭！
