### ISSUE TITLE
automated canary deployments with flagger and istio

### ISSUE THREAD

**Issue by haiker2011** [servicemesher/trans#215]
## 基本信息

原文链接：https://medium.com/google-cloud/automated-canary-deployments-with-flagger-and-istio-ac747827f9d1

发布时间：2019年2月21日

译文链接：

作者：Stefan Prodan

译者：

类型：博客

**Comment by shonge** [comment]
认领

**Comment by rootsongjc** [comment]
@shonge 你好，认领任务前请先加入到 ServiceMesher GitHub 组织，我已经邀请你了。
