### ISSUE TITLE
如何自定义Istio Mixer Adapter【源码】

### ISSUE THREAD

**Issue by hb-chen** [servicemesher/trans#219]
## 基本信息

原文链接：https://github.com/hb-chen/hbchen.com/blob/master/content/post/2019-03-05-custom-istio-mixer-adapter.md

发布时间：2019-03-05 

作者：Hobo Chen

类型：【博客】

**Comment by rootsongjc** [comment]
其中有个图挂了，需要修复下。

**Comment by hb-chen** [comment]
> 其中有个图挂了，需要修复下。

已修复

**Comment by rootsongjc** [comment]
已发布，参考https://juejin.im/post/5c7f982ee51d454cde7d5015
