### ISSUE TITLE
【Istio安全】服务间访问控制-RBAC

### ISSUE THREAD

**Issue by hb-chen** [servicemesher/trans#232]
## 基本信息

原文链接：http://hbchen.com/post/servicemesh/2019-03-09-istio-rbac-quick-start/
https://github.com/hb-chen/hbchen.com/blob/master/content/post/servicemesh/2019-03-09-istio-rbac-quick-start.md

发布时间：2019-03-22

作者：陈洪波

类型：【博客】

**Comment by rootsongjc** [comment]
已收录，将于近期发布，谢谢提交。
