### ISSUE TITLE
Guidance for Building a Control Plane for Envoy Part 3: Domain Specific Configuration

### ISSUE THREAD

**Issue by yangchuansheng** [servicemesher/trans#234]
## 基本信息

原文链接：https://medium.com/solo-io/guidance-for-building-a-control-plane-for-envoy-part-3-domain-specific-configuration-c97e8124b9d1

发布时间：2019年3月27日

译文链接：

作者：[Christian Posta](https://medium.com/@ceposta)

译者：孙海洲

类型：博客

**Comment by haiker2011** [comment]
认领
