### ISSUE TITLE
Envoy, Service Mesh and Observability Best Practices for Enterprises

### ISSUE THREAD

**Issue by rootsongjc** [servicemesher/trans#235]
## 基本信息

原文链接：https://medium.com/@ustela101/envoy-service-mesh-and-observability-best-practices-for-enterprises-6b72bbaa723c

发布时间：2019年3月11日

译文链接：

作者：Stela Udovicic

译者：张新峰

类型：博客

**Comment by haiker2011** [comment]
@zhangsean  已经认领有三个星期了，现在进展怎么样？

**Comment by rootsongjc** [comment]
发布完成，关闭 issue。
