### ISSUE TITLE
The service mesh era: Istio’s role in the future of hybrid cloud

### ISSUE THREAD

**Issue by yangchuansheng** [servicemesher/trans#236]
## 基本信息

原文链接：https://cloud.google.com/blog/topics/hybrid-cloud/the-service-mesh-era-istios-role-in-the-future-of-hybrid-cloud

发布时间：2019年4月2日

译文链接：

作者：[Megan O'Keefe](https://www.linkedin.com/in/meganaokeefe/)

译者：

类型：博客

**Comment by osswangxining** [comment]
@yangchuansheng @rootsongjc  I can help this, can assign to me?

**Comment by rootsongjc** [comment]
@osswangxining Assigned
