### ISSUE TITLE
Linkerd v2: How Lessons from Production Adoption Resulted in a Rewrite of the Service Mesh

### ISSUE THREAD

**Issue by rootsongjc** [servicemesher/trans#246]
## 基本信息

原文链接：https://www.infoq.com/articles/linkerd-v2-production-adoption

发布时间：2019年4月5日

译文链接：

作者：William Morgan

译者：

类型：博客

**Comment by haiker2011** [comment]
https://zhuanlan.zhihu.com/p/61617593 已翻译
