### ISSUE TITLE
Preventing Systemic Failure: Circuit Breaking—What it is and How it Works, Part 2

### ISSUE THREAD

**Issue by yangchuansheng** [servicemesher/trans#249]
## 类型

- [x] 翻译

## 文章信息

原文链接：https://glasnostic.com/blog/preventing-systemic-failure-circuit-breaking-part-2

原文发布时间：2019 年 3 月 19 日

译文链接：

作者：Yu-Han Lin

译者：

标签：

## 授权

- [x] 我已同意授权 ServiceMesher 公众号和 http://www.servicemesher.com 发布我原创或翻译的文章。

**Comment by GuangmingLuo** [comment]
accept
