### ISSUE TITLE
Vistio — Visualize your Istio Mesh Using Netflix’s Vizceral

### ISSUE THREAD

**Issue by rootsongjc** [servicemesher/trans#25]
## 基本信息

原文链接：https://itnext.io/vistio-visualize-your-istio-mesh-using-netflixs-vizceral-b075c402e18e

译文链接：

作者：Nick Nellis

译者：

类型：博客

**Comment by rootsongjc** [comment]
@loverto 不要一次认领多篇，待一篇合并后再认领另一篇。

**Comment by loverto** [comment]
好的
