### ISSUE TITLE
Benchmarking Istio & Linkerd CPU

### ISSUE THREAD

**Issue by skyao** [servicemesher/trans#252]
## 类型

- 翻译

## 当前进度

- [x] 已提交文章线索
- [x] 已有人认领翻译或为原创文章
- [x] 已提交 PR
- [x] 正在review
- [x] review 完成等待发布
- [x] 已发布到 http://www.servicemesher.com
- [x] 已发布到 ServiceMesher 微信公众号

## 文章信息

- 原文链接：https://medium.com/@michael_87395/benchmarking-istio-linkerd-cpu-c36287e32781
- 原文发布时间：2019-04-23
- 作者：Michael Kipper
- 标签： linkerd、istio

**Comment by rootsongjc** [comment]
已发布到官网：http://www.servicemesher.com/blog/the-service-mesh-era-istios-role-in-the-future-of-hybrid-cloud/

**Comment by malphi** [comment]
> 已发布到官网：http://www.servicemesher.com/blog/the-service-mesh-era-istios-role-in-the-future-of-hybrid-cloud/

link并不是这篇

**Comment by rootsongjc** [comment]
@malphi 我写错 URL 了，还没发布到官网。

**Comment by skyao** [comment]
https://skyao.io/post/201904-istio-performance-issue/

发的时候可以把我这个博客文章的地址带上，是关于这个评测文章的讨论和分析。

**Comment by rootsongjc** [comment]
发布完成，关闭 issue。
