### ISSUE TITLE
feat:增加Welcome、auto-comment和auto-assign GitHub Apps小机器人

### ISSUE THREAD

**Issue by haiker2011** [servicemesher/trans#257]
## feature描述
- 增加Welcome、auto-comment和auto-assign GitHub Apps小机器人，当有新的issue和PR时，会及时回复作者，也是对作者的一种重视。
- 提示内容可以自定义。

## 机器人使用组件
基于[probot框架](https://github.com/probot/probot)，查看[组件介绍页面](https://probot.github.io/)
- [Welcome机器人](https://probot.github.io/apps/welcome/)
- [Auto Assign机器人](https://probot.github.io/apps/auto-assign/)
- [Auto-comment机器人](https://probot.github.io/apps/auto-comment/)

## 自定义组件方式
通过在.github目录下放置对应的yaml配置文件
- auto-comment.yml配置Auto-comment机器人
- auto_assign.yml配置Auto Assign机器人
- config.yml 配置Welcome机器人

**Comment by rootsongjc** [comment]
能在 issue 中附上使用的github apps 的链接吗？可以让大家详细了解下。

**Comment by haiker2011** [comment]
@rootsongjc github apps 的链接已经添加

**Comment by haiker2011** [comment]
[Issue-Label-Bot](https://github.com/machine-learning-apps/Issue-Label-Bot)
Issue-Label-Bot是自动给issue添加标签的机器人，基于自然语言理解实现，当前还不是特别准确，没有添加。

**Comment by rootsongjc** [comment]
我们先使用下，有具体需求再调整配置。

**Comment by haiker2011** [comment]
@rootsongjc 关于机器人问题答复：
- [auto-comment]：当前主要是提示 committer 自检一些内容，主要是是否按照issue和PR模板提交，检查 title和内容是否符合我们的定义规范这个功能我要再去看看是否可以支持。
- [auto-assigned]：直接根据 OWNERS 文件来指派，这个功能我再去确认一下是否可行。
- [welcome]：回复一些有用的信息，例如提示 committer 自检一些内容。这个功能可以添加，我后续把提示信息完善一下。
