### ISSUE TITLE
feat:增加Mergify GitHub Apps小机器人 

### ISSUE THREAD

**Issue by haiker2011** [servicemesher/trans#267]
## feature描述
- 增加Mergify GitHub Apps小机器人 ，当有新的PR时，所有定义的Rules规则满足之后会自动合并PR。
- Rules规则可以自定义。

## 机器人使用组件
- [Mergify机器人](https://mergify.io/)

## 自定义组件方式
通过在根目录下放置对应的.mergify.yaml配置文件
- .mergify.yaml配置文件通过Rules 规则来配置Mergify机器人

**Comment by haiker2011** [comment]
Mergify最好能配合Prow自动打标签功能，才能真正发挥效力，真正实现**Stop** merging your pull requests manually, Mergify **automatically** merges pull requests when they're ready so you don't have to. You set the rules, it does the rest.

**Comment by chengwhynot** [comment]
想要什么时候打标签呢？
- 收到一个PR后标什么？
- 成功Merge后标什么？

**Comment by haiker2011** [comment]
@chengwhynot 打标签打算使用 Prow 来实现，暂时还没实现

**Comment by rootsongjc** [comment]
@chengwhynot @haiker2011  Prow 必须运行在 Kubernetes 集群里吧？
