### ISSUE TITLE
Translation: API Gateways and Service Meshes: Opening the Door to Application Modernisation

### ISSUE THREAD

**Issue by chengwhynot** [servicemesher/trans#273]
## 类型

本文的类型为：

原创

- [x] 翻译

转载

## 文章信息

- 原文链接：https://www.infoq.com/articles/api-gateway-service-mesh-app-modernisation

- 原文发布时间：MAY 03, 2019

- 作者：Daniel Bryant

- 标签：

## 当前进度

- [X] 已提交文章线索
- [ ] 已有人认领翻译或为原创文章
- [ ] 已提交 PR
- [ ] 正在review
- [ ] review 完成等待发布
- [ ] 已发布到 http://www.servicemesher.com
- [ ] 已发布到 ServiceMesher 微信公众号

**Comment by chengwhynot** [comment]
这是InfoQ的文章，不知道咱们能不能翻译。可以的话，我认领一下

**Comment by rootsongjc** [comment]
@chengwhynot 这篇文章我可以联系下 InfoQ 让他们授权我们翻译。

**Comment by rootsongjc** [comment]
@chengwhynot 这篇文章已经被 InfoQ 独家授权给其他人翻译，感谢你提供文章线索，这篇文章我们社区就不用翻译了。

**Comment by chengwhynot** [comment]
Ok
