### ISSUE TITLE
翻译： Benchmarking Istio & Linkerd CPU at Scale

### ISSUE THREAD

**Issue by zhangqx2010** [servicemesher/trans#279]
## 类型

本文的类型为：

翻译

## 文章信息

- 原文链接：https://medium.com/@michael_87395/benchmarking-istio-linkerd-cpu-at-scale-5f2cfc97c7fa

- 原文发布时间：2019-05-09

- 作者：Michael Kipper

- 标签：istio

## 当前进度

- [ ] 已提交文章线索
- [ ] 已有人认领翻译或为原创文章
- [ ] 已提交 PR
- [ ] 正在review
- [ ] review 完成等待发布
- [ ] 已发布到 http://www.servicemesher.com
- [ ] 已发布到 ServiceMesher 微信公众号

**Comment by haiker2011** [comment]
http://www.servicemesher.com/blog/benchmarking-istio-and-linkerd-cpu/  已完成翻译
