### ISSUE TITLE
建议直接将文章线索和文档提交到website 中

### ISSUE THREAD

**Issue by rootsongjc** [servicemesher/trans#283]
trans 这个 repo 一开始是为了让社区用户提交翻译和原创文章的，所有文章合并到该仓库中之后，我还要再搬运一遍到 [webiste](https://github.com/servicemesher/website) 中，因为制定的 Markdown 的 metadata 不同（文章顶部的 YAML 信息），所以每次搬运都要花费不少时间，况且写在 trans 这个 repo 中提交的文档最终都会发布到 website 中，而且跟 website 的 `content/blog` 结构是一致的，我建议以后所有 issue 和 PR 都提交到 webiste 中。@haiker2011 @SataQiu

**Comment by haiker2011** [comment]
@rootsongjc 我完全赞同，将文章线索和文档提交到website 中，也可以为以后做自动化打下基础，之后提交文档满足所有条件之后可以自动合并自动发布

**Comment by chengwhynot** [comment]
那我们怎么做呢？建立webhooks自动把issue复制到website里面？然后在那里面跟进，把这个trans的关闭掉？
还是通过别的自动化工具？
________________________________
发件人: Haiker Sun <notifications@github.com>
发送时间: 2019年5月10日 20:19
收件人: servicemesher/trans
抄送: Subscribed
主题: Re: [servicemesher/trans] 建议直接将文章线索和文档提交到website 中 (#283)


@rootsongjc<https://github.com/rootsongjc> 我完全赞同，将文章线索和文档提交到website 中，也可以为以后做自动化打下基础，之后提交文档满足所有条件之后可以自动合并自动发布

―

**Comment by rootsongjc** [comment]
@chengwhynot 先把 trans 里当前的 issue 都解决掉，不再接受新的 issue 和 PR 提交。
