### ISSUE TITLE
Service Mesh Architectures

### ISSUE THREAD

**Issue by rootsongjc** [servicemesher/trans#3]
## 基本信息

原文链接：https://blog.aspenmesh.io/blog/2018/03/service-mesh-architectures/

译文链接：

作者：aspenmesh.io

译者：张保珠

类型：架构

**Comment by ccc7574** [comment]
translating

**Comment by rootsongjc** [comment]
@ccc7574 这篇文章已经有2个周没有提交了，是否还要继续翻译？

**Comment by rootsongjc** [comment]
@ccc7574 是否翻译完成？如果完成请尽快提交PR，否则明天将取消指派重新分配该Issue。
