### ISSUE TITLE
Part 2: Rate Limiting for API gateways

### ISSUE THREAD

**Issue by rootsongjc** [servicemesher/trans#31]
## 基本信息

原文链接：https://blog.getambassador.io/rate-limiting-for-api-gateways-892310a2da02

译文链接：

作者：Daniel Bryant

译者：李昕阳

类型：博客

**Comment by edwin19861218** [comment]
领了

**Comment by rootsongjc** [comment]
@edwin19861218 请一次认领一篇，待翻译完成后再认领第二篇。

**Comment by darrenxyli** [comment]
I will take this one.

**Comment by rootsongjc** [comment]
@darrenxyli 感谢您的参与，请先加入到ServiceMesher GitHub组织。我已经邀请你了，请检查你的email。

**Comment by darrenxyli** [comment]
Working on this, plz assign to me. Thx
