### ISSUE TITLE
Part 3: Implementing a Java Rate Limiting Service for the Ambassador API Gateway

### ISSUE THREAD

**Issue by rootsongjc** [servicemesher/trans#32]
## 基本信息

原文链接：https://blog.getambassador.io/implementing-a-java-rate-limiting-service-for-the-ambassador-api-gateway-e09d542455da

译文链接：

作者：Daniel Bryant

译者：戴佳顺

类型：博客

**Comment by edwin19861218** [comment]
领了

**Comment by rootsongjc** [comment]
请翻译完一篇后，再认领第二篇。

**Comment by edwin19861218** [comment]
翻译中
