### ISSUE TITLE
Part 4: Designing a Rate Limiting Service for Ambassador

### ISSUE THREAD

**Issue by rootsongjc** [servicemesher/trans#33]
## 基本信息

原文链接：https://blog.getambassador.io/designing-a-rate-limiting-service-for-ambassador-f460e9fabedb

译文链接：

作者：Daniel Bryant

译者：

类型：博客

**Comment by edwin19861218** [comment]
领了

**Comment by rootsongjc** [comment]
请翻译完一篇后，再认领第二篇。

**Comment by edwin19861218** [comment]
翻译中
