### ISSUE TITLE
A/B testing on Kubernetes with Istio 0.8

### ISSUE THREAD

**Issue by rootsongjc** [servicemesher/trans#52]
## 基本信息

原文链接：https://medium.com/vamp-io/a-b-testing-on-kubernetes-with-istio-0-8-6323efa2b4e2

发布时间：2018年7月5日

译文链接：

作者：Alessandro Valcepina

译者：张琦翔

类型：【博客】

**Comment by zhangqx2010** [comment]
认领

**Comment by rootsongjc** [comment]
下次请注意文件名全小写。
