### ISSUE TITLE
istio源码分析之pilot-agent分析

### ISSUE THREAD

**Issue by SecretQY** [servicemesher/trans#57]
## 基本信息

原文链接：https://github.com/SecretQY/Service-Mesh/blob/master/istio%E6%BA%90%E7%A0%81%E5%88%86%E6%9E%90%E4%B9%8Bpilot-agent%E5%88%86%E6%9E%90%20.md

发布时间：2018-7-11

作者：丁轶群

类型：博客

**Comment by rootsongjc** [comment]
谢谢提交，已收录到原创系列。
