### ISSUE TITLE
Envoy 数据平面 APIs

### ISSUE THREAD

**Issue by junahan** [servicemesher/trans#59]
## 基本信息
介绍 Envoy 数据平面的由来和动机。

原文链接：https://blog.envoyproxy.io/the-universal-data-plane-api-d15cec7a

发布时间：2017-09

译文链接：https://github.com/junahan/JUNAHAN-A/blob/master/envoy-the-universal-data-plane-api-cn.org
作者：mattklein123 @lyft

译者：Junahan

类型：【博客】

**Comment by rootsongjc** [comment]
这篇文章已经翻译过了，见：http://www.servicemesher.com/blog/the-universal-data-plane-api/

**Comment by junahan** [comment]
没注意到，居然重复劳动了。

**Comment by rootsongjc** [comment]
下次领取和提交翻译前先提交Issue，然后再翻译，另外提交issue前先搜索下是否已经有人提交过。https://github.com/servicemesher/trans/issues/28 这是之前就提交和翻译完成的。
