### ISSUE TITLE
How Service Mesh Addresses 3 Major Microservices Challenges

### ISSUE THREAD

**Issue by rootsongjc** [servicemesher/trans#62]
## 基本信息

原文链接：https://dzone.com/articles/how-service-mesh-addresses-3-major-microservices-c

发布时间：2018年7月23日

译文链接：

作者：[Zach Jory](https://dzone.com/users/3206983/zjory.html)

译者：李昕阳

类型：博客

**Comment by darrenxyli** [comment]
认领
