### ISSUE TITLE
Service Mesh深度学习系列（三）| istio源码分析之pilot-discovery模块分析（中）

### ISSUE THREAD

**Issue by SecretQY** [servicemesher/trans#65]
## 基本信息

原文链接：https://github.com/SecretQY/Service-Mesh/blob/master/istio%E6%BA%90%E7%A0%81%E5%88%86%E6%9E%90%E4%B9%8Bpilot-discovery%E5%88%86%E6%9E%90(%E4%B8%AD).md

发布时间：2018.7.26

作者：丁轶群博士

译者：原创

类型：【博客】

**Comment by rootsongjc** [comment]
已发布，见 http://www.servicemesher.com/blog/istio-service-mesh-source-code-pilot-discovery-module-deepin-part2/
