### ISSUE TITLE
Istio Mixer Adapters.

### ISSUE THREAD

**Issue by yangwenmai** [servicemesher/trans#70]
## 基本信息

原文链接：https://hackernoon.com/istio-mixer-adapters-4004c7156c72

发布时间：2018-07-24

译文链接：

作者：Jeronimo (Jerry) Garcia

译者：

类型：【博客】

**Comment by rootsongjc** [comment]
@loverto 已经过了4天，翻译是否在进行中？如果没有的话将重新指派给别人。

**Comment by rootsongjc** [comment]
@loverto 已经过了7天，翻译是否在进行中？如果没有的话将重新指派给别人。

**Comment by rootsongjc** [comment]
@loverto 已经过了11天，翻译是否在进行中？如果没有的话将重新指派给别人。

**Comment by rootsongjc** [comment]
感觉这篇博客质量不够高啊

**Comment by loverto** [comment]
晚上我翻译一下吧

**Comment by loverto** [comment]
最近略忙

**Comment by rootsongjc** [comment]
我看还是先不用翻译了，这个文章太短了，写的内容又太简单，我关闭issue了。
