### ISSUE TITLE
Tracing services with Istio

### ISSUE THREAD

**Issue by yangwenmai** [servicemesher/trans#71]
## 基本信息

原文链接：https://hackernoon.com/tracing-services-with-istio-e51d249da60c

发布时间：2018-07-25

译文链接：

作者：Jeronimo (Jerry) Garcia

译者：

类型：【博客】

**Comment by yangwenmai** [comment]
认领

**Comment by rootsongjc** [comment]
@yangwenmai 已经过了4天，翻译是否在进行中？如果没有的话将重新指派给别人。

**Comment by yangwenmai** [comment]
#73 已经合并了。
