### ISSUE TITLE
Why You Should Care About Istio Gateways

### ISSUE THREAD

**Issue by rootsongjc** [servicemesher/trans#74]
## 基本信息

原文链接：https://thenewstack.io/why-you-should-care-about-istio-gateways/

发布时间：2018年8月2日

译文链接：

作者：Neeraj Poddar

译者：

类型：博客

**Comment by jianzi123** [comment]
认领

**Comment by rootsongjc** [comment]
@jianzi123 已经过了三天，翻译是否在进行中？如果没有的话将重新指派给别人。

**Comment by jianzi123** [comment]
翻译完了，晚上看下咋发。

**Comment by rootsongjc** [comment]
@jianzi123 翻译完了的话请提交PR吧
