### ISSUE TITLE
Enabling the Financial Services Shift to Microservices

### ISSUE THREAD

**Issue by rootsongjc** [servicemesher/trans#76]
## 基本信息

原文链接：https://aspenmesh.io/2018/08/enabling-the-financial-services-shift-to-microservices/

发布时间：2018年8月6日

译文链接：

作者：Zach Jory

译者：

类型：博客

**Comment by zhangqx2010** [comment]
认领

**Comment by rootsongjc** [comment]
重新分配给@meua
