### ISSUE TITLE
Application Safety and Correctness Cannot Be Offloaded to Istio or Any Service Mesh

### ISSUE THREAD

**Issue by rootsongjc** [servicemesher/trans#83]
## 基本信息

原文链接：http://blog.christianposta.com/microservices/application-safety-and-correctness-cannot-be-offloaded-to-istio-or-any-service-mesh/

发布时间：2018年8月10日

译文链接：http://www.servicemesher.com/blog/application-safety-and-correctness-cannot-be-offloaded-to-istio-or-any-service-mesh/

作者：Christian Posta

译者：陈冬

类型：博客

**Comment by shaobai** [comment]
认领
