### ISSUE TITLE
Securing Ingress Services in Istio with Let’s Encrypt on Kubernetes

### ISSUE THREAD

**Issue by rootsongjc** [servicemesher/trans#86]
## 基本信息

原文链接：https://medium.com/vamp-io/securing-ingress-services-in-istio-with-lets-encrypt-on-kubernetes-f6effd93ef06

发布时间：2018年8月15日

译文链接：

作者：Berk Gökden

译者：甄中元

类型：博客

**Comment by meua** [comment]
认领
