### ISSUE TITLE
Cilium 1.2: DNS Security Policies, EKS Support, ClusterMesh, kube-router integration, ...

### ISSUE THREAD

**Issue by rootsongjc** [servicemesher/trans#90]
## 基本信息

原文链接：https://cilium.io/blog/2018/08/21/cilium-12/

发布时间：2018年8月21日

译文链接：http://www.servicemesher.com/blog/cilium1.2-dns-security-policies-eks-support-clustermesh-kube-router-integration/

作者：Cilium

译者：甄中元

类型：博客

**Comment by meua** [comment]
认领
