### ISSUE TITLE
Increasing Security with a Service Mesh: Christian Posta Explores the Capabilities of Istio

### ISSUE THREAD

**Issue by rootsongjc** [servicemesher/trans#96]
## 基本信息

原文链接：https://www.infoq.com/articles/istio-security-mtls-jwt

发布时间：2018年8月16日

译文链接：

作者：Christian Posta

译者：

类型：博客

**Comment by roganw** [comment]
认领

**Comment by roganw** [comment]
pushed

**Comment by rootsongjc** [comment]
这个仓库目前还不支持关键字verb自动打label

**Comment by rootsongjc** [comment]
InfoQ的中文网站上已经发布了这篇文章了中文版了，http://www.infoq.com/cn/articles/istio-security-mtls-jwt @roganw
